name: more_calendars
description: A Project with various calendars types.
version: 0.0.1
homepage: https://github.com/RodolfoBonis/more_calendars

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
                                      